site_name: AI-Driven Hybrid Cloud Documentation Hub
site_description: Full-stack documentation of an enterprise-grade AI and cloud infrastructure simulation
theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Roboto Mono
    code: JetBrains Mono
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
extra_css:
  - assets/css/custom.css
nav:
  - Home: index.md
  - Phases:
      - Phase 1:
          On-Premise Infrastructure Setup: phases/1-onprem-bootstrap.md
      - Phase 2:
          Network Design and Security: phases/2-network-security.md
      - Phase 3:
          Cloud Foundations: phases/3-cloud-foundations.md
      - Phase 4:
          Cloud Migrations: phases/4-cloud-migrations.md
      - Phase 5:
          AI and Automation: phases/5-ai-automation.md
      - Phase 6:
          Monitoring and Observability: phases/6-observability.md
      - Phase 7:
          Reliability and Failure Simulation: phases/7-resilience-testing.md
  - Troubleshooting Vault: diagnostics/index.md
  - Homelab Engineering: homelab/index.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
                            
